const express = require("express");
const crypto = require("crypto");

const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const PORT = process.env.PORT || 10000;
const BASE_URL = (process.env.BASE_URL || "").replace(/\/$/, "");

const TIKTOK_CLIENT_KEY = process.env.TIKTOK_CLIENT_KEY;
const TIKTOK_CLIENT_SECRET = process.env.TIKTOK_CLIENT_SECRET;

const REDIRECT_URI = `${BASE_URL}/auth/tiktok/callback`;

// Start with the basic scope.
// Additional TikTok scopes may require approval.
const SCOPE = "user.info.basic";

// Temporary OAuth state/token storage.
// For testing only. A production application should use a database/session store.
const oauthTests = new Map();


// ----------------------------------------------------
// BASIC HOME PAGE
// ----------------------------------------------------

app.get("/", (req, res) => {
  res.send(`
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>JONTEZ TikTok OAuth Test</title>

  <style>
    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background: #111;
      color: #fff;
    }

    .container {
      max-width: 700px;
      margin: 50px auto;
      padding: 25px;
    }

    .card {
      background: #1c1c1c;
      border-radius: 18px;
      padding: 30px;
      box-shadow: 0 10px 40px rgba(0,0,0,.4);
    }

    h1 {
      margin-top: 0;
    }

    .status {
      padding: 14px;
      border-radius: 10px;
      background: #292929;
      margin: 15px 0;
      word-break: break-word;
    }

    .ok {
      color: #4cff88;
    }

    .bad {
      color: #ff6666;
    }

    button,
    a.button {
      display: inline-block;
      width: 100%;
      padding: 15px;
      margin-top: 15px;
      border: 0;
      border-radius: 10px;
      background: #fe2c55;
      color: white;
      font-size: 16px;
      font-weight: bold;
      text-decoration: none;
      cursor: pointer;
    }

    button:hover,
    a.button:hover {
      opacity: .9;
    }

    code {
      background: #000;
      padding: 3px 6px;
      border-radius: 5px;
      word-break: break-all;
    }

    .small {
      font-size: 13px;
      color: #aaa;
      line-height: 1.6;
    }
  </style>
</head>

<body>

<div class="container">
  <div class="card">

    <h1>JONTEZ TikTok OAuth Test</h1>

    <p>
      This is a separate TikTok Sandbox OAuth testing server.
    </p>

    <div class="status">
      <strong>Client Key:</strong>
      <span class="${TIKTOK_CLIENT_KEY ? "ok" : "bad"}">
        ${TIKTOK_CLIENT_KEY ? "Configured" : "Missing"}
      </span>
    </div>

    <div class="status">
      <strong>Client Secret:</strong>
      <span class="${TIKTOK_CLIENT_SECRET ? "ok" : "bad"}">
        ${TIKTOK_CLIENT_SECRET ? "Configured" : "Missing"}
      </span>
    </div>

    <div class="status">
      <strong>Base URL:</strong><br>
      <code>${escapeHtml(BASE_URL || "NOT CONFIGURED")}</code>
    </div>

    <div class="status">
      <strong>Redirect URI:</strong><br>
      <code>${escapeHtml(REDIRECT_URI)}</code>
    </div>

    <div class="status">
      <strong>Scope:</strong>
      <code>${SCOPE}</code>
    </div>

    <a class="button" href="/termux/start">
      Start TikTok OAuth
    </a>

    <p class="small">
      The OAuth authorization request is generated by this server.
      Your TikTok client secret is never placed in the browser.
    </p>

  </div>
</div>

</body>
</html>
  `);
});


// ----------------------------------------------------
// HEALTH CHECK
// ----------------------------------------------------

app.get("/health", (req, res) => {
  res.json({
    ok: true,
    service: "JONTEZ TikTok OAuth Test",
    status: "running",
    port: PORT,
    base_url: BASE_URL,
    redirect_uri: REDIRECT_URI,
    scope: SCOPE,
    client_key_configured: Boolean(TIKTOK_CLIENT_KEY),
    client_secret_configured: Boolean(TIKTOK_CLIENT_SECRET)
  });
});


// ----------------------------------------------------
// START OAUTH
// ----------------------------------------------------

app.get("/termux/start", (req, res) => {

  if (!TIKTOK_CLIENT_KEY) {
    return res.status(500).json({
      error: "missing_client_key"
    });
  }

  if (!BASE_URL) {
    return res.status(500).json({
      error: "missing_base_url"
    });
  }

  const state = crypto.randomBytes(32).toString("hex");

  oauthTests.set(state, {
    createdAt: Date.now()
  });

  const params = new URLSearchParams({
    client_key: TIKTOK_CLIENT_KEY,
    response_type: "code",
    scope: SCOPE,
    redirect_uri: REDIRECT_URI,
    state: state
  });

  const authorizationUrl =
    `https://www.tiktok.com/v2/auth/authorize/?${params.toString()}`;

  res.json({
    success: true,
    authorization_url: authorizationUrl,
    state: state,
    redirect_uri: REDIRECT_URI,
    scope: SCOPE
  });
});


// ----------------------------------------------------
// TIKTOK CALLBACK
// ----------------------------------------------------

app.get("/auth/tiktok/callback", async (req, res) => {

  const { code, state, error, error_description } = req.query;

  if (error) {
    return res.status(400).send(`
      <html>
      <body style="font-family:Arial;padding:30px">
        <h1>TikTok OAuth Error</h1>
        <p><strong>Error:</strong> ${escapeHtml(error)}</p>
        <p><strong>Description:</strong> ${escapeHtml(error_description || "")}</p>
        <p><a href="/">Back</a></p>
      </body>
      </html>
    `);
  }

  if (!code) {
    return res.status(400).send("Missing authorization code.");
  }

  if (!state) {
    return res.status(400).send("Missing OAuth state.");
  }

  const test = oauthTests.get(state);

  if (!test) {
    return res.status(400).send(`
      <h1>Invalid or expired state</h1>
      <p>Start the OAuth process again.</p>
      <p><a href="/">Back</a></p>
    `);
  }

  // Delete state immediately so it cannot be reused.
  oauthTests.delete(state);

  if (!TIKTOK_CLIENT_SECRET) {
    return res.status(500).send("TikTok client secret is not configured.");
  }

  try {

    const tokenResponse = await fetch(
      "https://open.tiktokapis.com/v2/oauth/token/",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body: new URLSearchParams({
          client_key: TIKTOK_CLIENT_KEY,
          client_secret: TIKTOK_CLIENT_SECRET,
          code: code,
          grant_type: "authorization_code",
          redirect_uri: REDIRECT_URI
        })
      }
    );

    const tokenText = await tokenResponse.text();

    let tokenData;

    try {
      tokenData = JSON.parse(tokenText);
    } catch {
      tokenData = {
        raw_response: tokenText
      };
    }

    if (!tokenResponse.ok) {
      return res.status(400).send(`
        <html>
        <body style="font-family:Arial;padding:30px">
          <h1>Token Exchange Failed</h1>

          <p>HTTP status: ${tokenResponse.status}</p>

          <pre style="
            background:#111;
            color:#fff;
            padding:20px;
            border-radius:10px;
            overflow:auto;
          ">${escapeHtml(JSON.stringify(tokenData, null, 2))}</pre>

          <p><a href="/">Try again</a></p>
        </body>
        </html>
      `);
    }

    // Store token temporarily.
    oauthTests.set(state, {
      createdAt: Date.now(),
      tokenData
    });

    res.send(`
      <html>
      <head>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>TikTok OAuth Success</title>

        <style>
          body {
            background:#111;
            color:#fff;
            font-family:Arial;
            padding:25px;
          }

          .card {
            max-width:800px;
            margin:auto;
            background:#1c1c1c;
            padding:25px;
            border-radius:15px;
          }

          pre {
            background:#000;
            padding:20px;
            border-radius:10px;
            overflow:auto;
            white-space:pre-wrap;
            word-break:break-word;
          }

          a {
            color:#4cff88;
          }
        </style>
      </head>

      <body>

        <div class="card">

          <h1>✅ TikTok OAuth Successful</h1>

          <p>
            TikTok authorization code was successfully exchanged
            for an access token.
          </p>

          <h3>Token Response</h3>

          <pre>${escapeHtml(JSON.stringify(tokenData, null, 2))}</pre>

          <p>
            <strong>Important:</strong>
            Do not share the access token or refresh token publicly.
          </p>

          <p>
            State:
            <code>${escapeHtml(state)}</code>
          </p>

          <p>
            <a href="/termux/access-token?state=${encodeURIComponent(state)}">
              View access-token test response
            </a>
          </p>

          <p>
            <a href="/">Return home</a>
          </p>

        </div>

      </body>
      </html>
    `);

  } catch (err) {

    console.error("Token exchange error:", err);

    res.status(500).send(`
      <html>
      <body style="font-family:Arial;padding:30px">
        <h1>Server Error</h1>
        <pre>${escapeHtml(err.message)}</pre>
        <p><a href="/">Back</a></p>
      </body>
      </html>
    `);
  }
});


// ----------------------------------------------------
// TOKEN RESULT
// ----------------------------------------------------

app.get("/termux/result", (req, res) => {

  const { state } = req.query;

  if (!state) {
    return res.status(400).json({
      error: "missing_state"
    });
  }

  const test = oauthTests.get(state);

  if (!test) {
    return res.status(404).json({
      error: "result_not_found",
      message: "The OAuth result does not exist or has already been retrieved."
    });
  }

  oauthTests.delete(state);

  res.json({
    success: true,
    token_response: test.tokenData
  });
});


// ----------------------------------------------------
// ACCESS TOKEN ONLY
// ----------------------------------------------------

app.get("/termux/access-token", (req, res) => {

  const { state } = req.query;

  if (!state) {
    return res.status(400).json({
      error: "missing_state"
    });
  }

  const test = oauthTests.get(state);

  if (!test || !test.tokenData) {
    return res.status(404).json({
      error: "access_token_not_found"
    });
  }

  oauthTests.delete(state);

  res.json({
    success: true,
    access_token: test.tokenData.access_token || null,
    open_id: test.tokenData.open_id || null,
    scope: test.tokenData.scope || null,
    expires_in: test.tokenData.expires_in || null,
    refresh_expires_in: test.tokenData.refresh_expires_in || null
  });
});


// ----------------------------------------------------
// PRIVACY
// ----------------------------------------------------

app.get("/privacy", (req, res) => {
  res.send(`
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Privacy Policy</title>
</head>

<body style="font-family:Arial;max-width:800px;margin:40px auto;padding:20px">

<h1>Privacy Policy</h1>

<p>
JONTEZ TikTok OAuth Test is a technical testing application
used to test TikTok Login and OAuth functionality.
</p>

<h2>Information</h2>

<p>
During OAuth testing, TikTok may provide information such as
a TikTok open ID, access token, refresh token, and basic account
information permitted by the authorized scope.
</p>

<h2>Use of Information</h2>

<p>
Information received through TikTok OAuth is used only for
testing and demonstrating the application's authentication
functionality.
</p>

<h2>Storage</h2>

<p>
OAuth test information is temporarily held in server memory
for testing purposes. It is not intended to be a permanent
production data store.
</p>

<h2>Security</h2>

<p>
Client secrets and tokens should never be published in source
code or shared publicly.
</p>

<h2>Contact</h2>

<p>
JONTEZ
</p>

</body>
</html>
  `);
});


// ----------------------------------------------------
// TERMS
// ----------------------------------------------------

app.get("/terms", (req, res) => {
  res.send(`
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Terms of Service</title>
</head>

<body style="font-family:Arial;max-width:800px;margin:40px auto;padding:20px">

<h1>Terms of Service</h1>

<p>
JONTEZ TikTok OAuth Test is provided as a technical testing
application for TikTok OAuth functionality.
</p>

<h2>Use</h2>

<p>
Users should use the application only for lawful testing and
development purposes.
</p>

<h2>Third-Party Services</h2>

<p>
The application interacts with TikTok services. TikTok accounts
and TikTok services remain subject to TikTok's own terms and
policies.
</p>

<h2>Tokens</h2>

<p>
Users should not share access tokens, refresh tokens, client
secrets, or other authentication credentials.
</p>

<h2>Availability</h2>

<p>
This testing application may be modified, interrupted, or
removed without notice.
</p>

<h2>Contact</h2>

<p>
JONTEZ
</p>

</body>
</html>
  `);
});


// ----------------------------------------------------
// 404
// ----------------------------------------------------

app.use((req, res) => {
  res.status(404).json({
    error: "not_found",
    path: req.path
  });
});


// ----------------------------------------------------
// HELPER
// ----------------------------------------------------

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}


// ----------------------------------------------------
// START SERVER
// ----------------------------------------------------

app.listen(PORT, "0.0.0.0", () => {

  console.log("========================================");
  console.log("JONTEZ TIKTOK OAUTH TEST SERVER");
  console.log("========================================");
  console.log(`Port: ${PORT}`);
  console.log(`Base URL: ${BASE_URL}`);
  console.log(`Client Key configured: ${Boolean(TIKTOK_CLIENT_KEY)}`);
  console.log(`Client Secret configured: ${Boolean(TIKTOK_CLIENT_SECRET)}`);
  console.log(`OAuth Redirect URI: ${REDIRECT_URI}`);
  console.log(`Scope: ${SCOPE}`);
  console.log("========================================");

});
